In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [23]:
##Find the shape, number of dimensions, data type, size and type of each array.

# Create a 1-dimensional NumPy array using np.array()

a1 = np.array([1,2,3])
a1.shape, a1.ndim, a1.dtype, a1.size

((3,), 1, dtype('int32'), 3)

In [22]:
# Create a 2-dimensional NumPy array using np.array()

a2 = np.array([[1,2,3,],
               [4,5,6]])

a2.shape, a2.ndim, a2.dtype, a2.size


((2, 3), 2, dtype('int32'), 6)

In [21]:
# Create a 3-dimensional Numpy array using np.array()

a3 = np.array([[[1,2,3], 
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])
               

a3.shape, a3.ndim, a3.dtype, a3.size


((2, 3, 3), 3, dtype('int32'), 18)

In [28]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

demoframe = pd.DataFrame(a2)
demoframe

0  1  2
0  1  2  3
1  4  5  6

In [33]:
# Create an array of shape (10, 2) with only ones

one = np.ones(shape= (10, 2))
one

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
# Create an array of shape (7, 2, 3) of only zeros

zero = np.zeros(shape= (7,2,3) )
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
# Create an array within a range of 0 and 100 with step 3

range_array = np.arange(0, 100, 3)
range_array


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [45]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

random_array_1 = np.random.randint(10,size = (7,2))
random_array_1

array([[5, 8],
       [1, 1],
       [2, 7],
       [6, 9],
       [5, 7],
       [9, 5],
       [2, 4]])

In [50]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

random_array_2 = np.random.rand(3,5)
random_array_2

array([[0.78616855, 0.44174958, 0.30524442, 0.32636571, 0.70255632],
       [0.50351336, 0.83176118, 0.61404585, 0.59742908, 0.03836146],
       [0.1870664 , 0.7305526 , 0.22076092, 0.43623895, 0.23732536]])

In [53]:
# Set the random seed to 42
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.seed(42)

random_array_3 = np.random.randint(10,size =(4,6))
random_array_3


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [56]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

demo_array = np.random.randint(10,size=(3,7))
demo_array

array([[3, 7, 6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8, 0, 8],
       [6, 8, 7, 0, 7, 7, 2]])

In [59]:
# Find the unique numbers in the array you just created

np.unique(demo_array)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [60]:
# Find the 0'th index of the latest array you created
demo_array[0]

array([3, 7, 6, 8, 7, 4, 1])

In [64]:
# Get the first 2 rows of latest array you created
demo_array[:2,:]

array([[3, 7, 6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8, 0, 8]])

In [65]:
# Get the first 2 values of the first 2 rows of the latest array

demo_array[:2,:2]

array([[3, 7],
       [4, 7]])

In [70]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

random_array_4 = np.random.randint(10,size = (3,5))
ones_array_2 = np.ones((3,5))
random_array_4, ones_array_2


(array([[6, 6, 8, 9, 9],
        [2, 6, 0, 3, 3],
        [4, 6, 6, 3, 6]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [72]:
# Add the two arrays together
random_array_4 + ones_array_2

# np.sum(random_array_4+ones_array_2)  # This will

array([[ 7.,  7.,  9., 10., 10.],
       [ 3.,  7.,  1.,  4.,  4.],
       [ 5.,  7.,  7.,  4.,  7.]])

In [73]:
# Create another array of ones of shape (5, 3)

ones_array_3 = np.ones(shape=(5, 3))

In [76]:
# Try add the array of ones and the other most recent array together

random_array_4 + ones_array_3

# When you try the last cell, it produces an error. Why do think this is?
# How would you fix it?

# random_array_4 + ones_array_3.reshape(3,5) ------>solution


array([[ 7.,  7.,  9., 10., 10.],
       [ 3.,  7.,  1.,  4.,  4.],
       [ 5.,  7.,  7.,  4.,  7.]])

In [77]:
# Create another array of ones of shape (3, 5)

ones_array_4 = np.ones(shape=(3, 5))

In [79]:
# Subtract the new array of ones from the other most recent array

random_array_4 - ones_array_4 

array([[ 5.,  5.,  7.,  8.,  8.],
       [ 1.,  5., -1.,  2.,  2.],
       [ 3.,  5.,  5.,  2.,  5.]])

In [80]:
# Multiply the ones array with the latest array

random_array_4 * ones_array_4

array([[6., 6., 8., 9., 9.],
       [2., 6., 0., 3., 3.],
       [4., 6., 6., 3., 6.]])

In [83]:
# Take the latest array to the power of 2 using '**'

random_array_4 ** 2

array([[36, 36, 64, 81, 81],
       [ 4, 36,  0,  9,  9],
       [16, 36, 36,  9, 36]])

In [84]:
# Do the same thing with np.square()

np.square(random_array_4)

array([[36, 36, 64, 81, 81],
       [ 4, 36,  0,  9,  9],
       [16, 36, 36,  9, 36]])

In [85]:
# Find the mean of the latest array using np.mean()

np.mean(random_array_4)

5.133333333333334

In [86]:
# Find the maximum of the latest array using np.max()

np.max(random_array_4)

9

In [87]:
# Find the minimum of the latest array using np.min()

np.min(random_array_4)

0

In [88]:
# Find the standard deviation of the latest array

np.std(random_array_4)

2.4997777679003566

In [90]:
# Find the variance of the latest array

np.var(random_array_4)

6.24888888888889

In [91]:
# Reshape the latest array to (3, 5, 1)

random_array_4.reshape(3,5,1)

array([[[6],
        [6],
        [8],
        [9],
        [9]],

       [[2],
        [6],
        [0],
        [3],
        [3]],

       [[4],
        [6],
        [6],
        [3],
        [6]]])

In [96]:
# Transpose the latest array

random_array_4.T

array([[6, 2, 4],
       [6, 6, 6],
       [8, 0, 6],
       [9, 3, 3],
       [9, 3, 6]])

In [98]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

random_array_5 = np.random.randint(10, size = (3,3))
random_array_6 = np.random.randint(10,size =(3,2))

In [99]:
# Perform a dot product on the two newest arrays you created

random_array_5.dot(random_array_6)

array([[ 42,  24],
       [102, 104],
       [ 48, 112]])

In [101]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

random_array_7 = np.random.randint(10,size=(4,3))
random_array_8 = np.random.randint(10,size=(4,3))

In [105]:
# Perform a dot product on the two newest arrays you created
random_array_7.dot(random_array_8)

# It doesn't work. How would you fix it?
# random_array_7.dot(random_array_8.reshape(3,4)) -----> Solution


array([[ 89,  88,  64, 107],
       [ 47,  40,  19,  80],
       [ 85,  59,  53, 136],
       [ 33,  54,   9,  36]])

In [106]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

random_array_7.dot(random_array_8.T) 


array([[127,  73,  51,  67],
       [ 79,  34,  69,  28],
       [117,  80,  84,  58],
       [ 73,   6,  45,  20]])

In [107]:
# Compare the two arrays with '>'
random_array_7 > random_array_8


array([[ True, False,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [112]:
# Compare the two arrays with '>='

random_array_7 >= random_array_8



array([[ True, False,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [109]:
# Find which elements of the first array are greater than 7

random_array_7 > 7


array([[ True, False,  True],
       [False, False, False],
       [False,  True, False],
       [False, False,  True]])

In [110]:
# Which parts of each array are equal? (try using '==')

random_array_7 == random_array_8


array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [113]:
# Sort one of the arrays you just created in ascending order

np.sort(random_array_7)

array([[3, 8, 8],
       [2, 5, 6],
       [4, 7, 8],
       [0, 2, 9]])

In [114]:
# Sort the indexes of one of the arrays you just created

np.argsort(random_array_7)

array([[1, 0, 2],
       [0, 2, 1],
       [2, 0, 1],
       [0, 1, 2]], dtype=int64)

In [121]:
# Find the index with the maximum value in one of the arrays you've created

np.argmax(random_array_7)

11

In [117]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array_7)

9

In [122]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

np.argmax(random_array_7 , axis=1)

array([0, 1, 1, 2], dtype=int64)

In [123]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

np.argmin(random_array_7,axis= 0)

array([3, 3, 2], dtype=int64)

In [124]:
random_array_7

array([[8, 3, 8],
       [2, 6, 5],
       [7, 8, 4],
       [0, 2, 9]])

In [126]:
# Create an array of normally distributed random numbers

np.random.randn(3,5)

array([[ 0.79103195, -0.90938745,  1.40279431, -1.40185106,  0.58685709],
       [ 2.19045563, -0.99053633, -0.56629773,  0.09965137, -0.50347565],
       [-1.55066343,  0.06856297, -1.06230371,  0.47359243, -0.91942423]])

In [127]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])